name: Run tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "**"
jobs:
    deploy-web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
